name: aerospike-tools-backup

dependency:
  - url: git@github.com:citrusleaf/aerospike-client-c
    dir: client

container:
  - base:
      - docker.qe.aerospike.com/build/aerospike-tools:centos-6
      - docker.qe.aerospike.com/build/aerospike-tools:centos-7
      - docker.qe.aerospike.com/build/aerospike-tools:centos-8
      - docker.qe.aerospike.com/build/aerospike-tools:debian-8
      - docker.qe.aerospike.com/build/aerospike-tools:debian-9
      - docker.qe.aerospike.com/build/aerospike-tools:debian-10
      - docker.qe.aerospike.com/build/aerospike-tools:ubuntu-14.04
      - docker.qe.aerospike.com/build/aerospike-tools:ubuntu-16.04
      - docker.qe.aerospike.com/build/aerospike-tools:ubuntu-18.04

build:
  - name: default
    environment:
      CLIENTREPO: /work/source/client
    script:
      - make -C client
      - make
    artifact:
      - bin/*
