# Base Image
FROM registry.access.redhat.com/ubi10/ubi-minimal

# Environment Variables
ENV PKG=rpm \
    GOROOT=/usr/local/go \
    GO_VERSION=1.23.11 \
    LIBCURL_VERSION=curl-7_83_1 \
    LIBJANSSON_VERSION=v2.14 \
    AWS_SDK_CPP_VERSION=1.10.55 \
    READLINE_VERSION=8.2 \
    FLEX_VERSION=2.6.4

ENV PATH=$PATH:$GOROOT/bin:/work/bin

# Install Required Packages
RUN microdnf install -y \
    cmake \
    git \
    rsync \
    tar \
    wget \
    libffi-devel \
    zlib-devel \
    make \
    gcc \
    gcc-c++ \
    autoconf \
    automake \
    libtool \
    bzip2-devel \
    sqlite-devel \
    xz-devel \
    ncurses-devel \
    rpm-build \
    redhat-rpm-config \
    && microdnf clean all


WORKDIR /work/source
# Install OpenSSL from source
ADD script/installOpenSSL.sh /work/source/installOpenSSL.sh
RUN microdnf install -y \
    perl \
    perl-devel \
    glibc-devel \
    bzip2 \
    expat-devel \
    && microdnf clean all
RUN bash installOpenSSL.sh x86_64

# Create working directory
WORKDIR /work/

# install readline-devel from source
RUN wget http://ftp.gnu.org/gnu/readline/readline-${READLINE_VERSION}.tar.gz && \
    tar -xzf readline-${READLINE_VERSION}.tar.gz && \
    cd readline-${READLINE_VERSION} && \
    ./configure --prefix=/usr --includedir=/usr/include --libdir=/usr/lib && \
    make SHLIB_LIBS="-lncurses -ltinfo" && \
    make install

# Pyenv install and setup for python version management.
RUN curl https://pyenv.run | bash
ENV PYENV_ROOT=/root/.pyenv
ENV PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
ENV PYTHON_CONFIGURE_OPTS="--enable-shared"
# Choose which version of python to bundle with asadm.
# Will automatically grab the latest bug fix.
ENV PYTHON_VERSION=3.10
# Set the version of python to be bundled with asadm.
RUN pyenv install ${PYTHON_VERSION}:latest -v
RUN pyenv global ${PYTHON_VERSION}
# # Install pipenv for enviornement management.
RUN pip install pipenv

# Create working directory
WORKDIR /work/

# Source install of libjansson
RUN git clone https://github.com/akheron/jansson.git && \
    cd jansson && \
    git checkout tags/${LIBJANSSON_VERSION} && \
    autoreconf -i && \
    ./configure && \
    make && \
    make install

# Source install of libyaml
RUN git clone https://github.com/yaml/libyaml && \
    cd libyaml && \
    ./bootstrap && \
    ./configure && \
    make && \
    make install

# Source install of zstd
RUN git clone https://github.com/facebook/zstd.git && \
    cd zstd && \
    make && \
    make install

# Commands are run from the source directory
WORKDIR /work/source

# Source install of libcurl
RUN git clone https://github.com/curl/curl.git && \
    cd curl && \
    git checkout tags/${LIBCURL_VERSION} && \
    mkdir build && cd build && \
    cmake /work/source/curl -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=lib -DBUILD_SHARED_LIBS=OFF -DBUILD_CURL_EXE=OFF && \
    make && \
    make install

# Install Go
WORKDIR /work
RUN wget https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz && \
    tar -xzf go${GO_VERSION}.linux-amd64.tar.gz && \
    mv go /usr/local

# Source install of aws-sdk-cpp
WORKDIR /work/source
RUN git clone https://github.com/aws/aws-sdk-cpp.git && \
    cd aws-sdk-cpp && \
    git checkout tags/${AWS_SDK_CPP_VERSION} && \
    git submodule update --init --recursive && \
    mkdir build && cd build && \
    cmake /work/source/aws-sdk-cpp -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=lib -DBUILD_ONLY="s3" -DENABLE_TESTING=OFF -DBUILD_SHARED_LIBS=OFF -DENABLE_UNITY_BUILD=ON && \
    make && \
    make install && \
    rm -rf /work/source/aws-sdk-cpp

# Add async c-client support
WORKDIR /work/source
RUN git clone https://github.com/libuv/libuv && \
    cd libuv && \
    git fetch --all --tags && \
    git checkout tags/v1.42.0 && \
    sh autogen.sh && \
    ./configure && \
    make && \
    make install
# cleanup libuv source
RUN rm -rf /work/source/libuv

# install flex / lex
WORKDIR /work/source
RUN wget https://github.com/westes/flex/releases/download/v${FLEX_VERSION}/flex-${FLEX_VERSION}.tar.gz && \
    tar -xvzf flex-${FLEX_VERSION}.tar.gz && \
    cd flex-${FLEX_VERSION} && \
    ./configure --prefix=/usr && \
    make -j$(nproc) && \
    make install && \
    ln -s /usr/bin/flex /usr/bin/lex
