FROM redhat/ubi9
SHELL ["/bin/bash", "-euox", "pipefail", "-c"]
RUN useradd -u 9001 -m build

ADD .github/docker/entrypoint.sh /tmp/entrypoint.sh
ADD .github/docker/install_deps.sh /tmp/install_deps.sh

RUN source /tmp/install_deps.sh && install_deps_redhat-ubi9
ADD --chown=build:build . /opt/asbackup
USER build

WORKDIR /opt/asbackup
ENTRYPOINT ["/opt/asbackup/.github/docker/entrypoint.sh"]
CMD ["-b"]
